### ISSUE TITLE
录制视频和生成出来的视频 都是被拉伸过的，对着电脑拍就很明显的看出来

### ISSUE THREAD

**Issue by qingyangCode** [jarvisyin/SquareVideoRecorder#3]
如上

**Comment by t14z** [comment]
可能是角度问题吧，您有测量过吗？我这边的计算确实是正方形呀

**Comment by qingyangCode** [comment]
最近有空仔细研究了下demo，经过稍微修改下参数，录制的视频是可以使用的：
非常感谢博主提供的demo

   openCamera () {
           ........
        CameraUtils.choosePreviewSize(parameters, mContext.DESIRED_WIDTH, mContext.DESIRED_HEIGHT);
           ........
   }

在openCamera 的时候，这里Camera 的 preview Size 不能自己指定，使用Camera支持的列表中的Preview Size就可以了。

在 FinalVideoCreator  里的 createVideo 方法中，saveVideo 的尺寸可以自己指定
private void createVideo() throws Exception {
           ..........
MediaFormat outputVideoFormat = MediaFormat.createVideoFormat(OUTPUT_VIDEO_MIME_TYPE, 720, 720);
           ..........
}
